// Flat-config for ESLint 9+. Covers the browser-facing game script and the
// Node-run test file (both use the same script, loaded differently).
export default [
  {
    files: ['script.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        location: 'readonly',
        URLSearchParams: 'readonly',
        console: 'readonly',
        Image: 'readonly',
        localStorage: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        AudioContext: 'readonly',
        webkitAudioContext: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        process: 'readonly',
        global: 'writable',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'warn',
      eqeqeq: ['error', 'smart'],
      'no-implicit-globals': 'off',
    },
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        cancelAnimationFrame: 'readonly',
        requestAnimationFrame: 'readonly',
        localStorage: 'readonly',
        navigator: 'readonly',
        // Exposed by script.js in test mode:
        game: 'readonly',
        GAME_CONFIG: 'readonly',
        STATE: 'readonly',
        canvas: 'readonly',
        ctx: 'readonly',
        dino: 'readonly',
        getBackgroundColor: 'readonly',
        drawBackground: 'readonly',
        starFadeAlpha: 'readonly',
        initClouds: 'readonly',
        updateClouds: 'readonly',
        drawClouds: 'readonly',
        drawGround: 'readonly',
        spawnObstacle: 'readonly',
        updateObstacles: 'readonly',
        drawObstacles: 'readonly',
        drawScore: 'readonly',
        drawDino: 'readonly',
        checkCollision: 'readonly',
        jump: 'readonly',
        resetGame: 'readonly',
        gameLoop: 'readonly',
        drawGameOverScreen: 'readonly',
        Animations: 'readonly',
        DifficultyProfile: 'readonly',
        FEATURES: 'readonly',
        MODES: 'readonly',
        Particles: 'readonly',
        ScoreStore: 'readonly',
        a11yLive: 'readonly',
        announce: 'readonly',
        audio: 'readonly',
        cfg: 'readonly',
        computeRunResult: 'readonly',
        dailyNumber: 'readonly',
        dailySeed: 'readonly',
        refreshDailyButton: 'readonly',
        drawGetReadyOverlay: 'readonly',
        drawIdleScreen: 'readonly',
        drawNewBestBadge: 'readonly',
        drawDeathFlash: 'readonly',
        deathFlashPeakAlpha: 'readonly',
        drawSkyTint: 'readonly',
        skyTintPeakAlpha: 'readonly',
        getHillColor: 'readonly',
        handleAction: 'readonly',
        handleResize: 'readonly',
        initCanvasScale: 'readonly',
        initHills: 'readonly',
        loadMode: 'readonly',
        loadTuning: 'readonly',
        mulberry32: 'readonly',
        runFeatureDraws: 'readonly',
        saveTuning: 'readonly',
        setMode: 'readonly',
        setReducedMotion: 'readonly',
        setQaPlateau: 'readonly',
        readQaPlateauFlag: 'readonly',
        QA_PLATEAU_SCORE: 'readonly',
        setQaCluster: 'readonly',
        readQaClusterFlag: 'readonly',
        setQaBig: 'readonly',
        readQaBigFlag: 'readonly',
        setQaNight: 'readonly',
        readQaNightFlag: 'readonly',
        setQaLevel: 'readonly',
        readQaLevelFlag: 'readonly',
        setQaTrail: 'readonly',
        readQaTrailFlag: 'readonly',
        setQaConfetti: 'readonly',
        readQaConfettiFlag: 'readonly',
        obstacleNightBrightness: 'readonly',
        dinoNightBrightness: 'readonly',
        cloudPaintAlpha: 'readonly',
        groundPaintAlpha: 'readonly',
        landDustColor: 'readonly',
        shareDailyResult: 'readonly',
        STATE_HANDLERS: 'readonly',
        updateHills: 'readonly',
        enableDeathLog: 'readonly',
        disableDeathLog: 'readonly',
        isDeathLogEnabled: 'readonly',
        applyDebugFromLocation: 'readonly',
        replayRunSeed: 'readonly',
        dumpRun: 'readonly',
        copyDeathLog: 'readonly',
        handleDebugKey: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
    },
  },
];
