// Flat-config for ESLint 9+. Covers the browser-facing game script and the
// Node-run test file (both use the same script, loaded differently).
export default [
  {
    files: ['script.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        Image: 'readonly',
        localStorage: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        process: 'readonly',
        global: 'writable',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
      'no-var': 'error',
      'prefer-const': 'warn',
      eqeqeq: ['error', 'smart'],
      'no-implicit-globals': 'off',
    },
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        process: 'readonly',
        require: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        cancelAnimationFrame: 'readonly',
        requestAnimationFrame: 'readonly',
        localStorage: 'readonly',
        // Exposed by script.js in test mode:
        game: 'readonly',
        GAME_CONFIG: 'readonly',
        STATE: 'readonly',
        canvas: 'readonly',
        ctx: 'readonly',
        dino: 'readonly',
        getBackgroundColor: 'readonly',
        drawBackground: 'readonly',
        initClouds: 'readonly',
        updateClouds: 'readonly',
        drawClouds: 'readonly',
        spawnObstacle: 'readonly',
        updateObstacles: 'readonly',
        drawObstacles: 'readonly',
        drawScore: 'readonly',
        drawDino: 'readonly',
        checkCollision: 'readonly',
        jump: 'readonly',
        resetGame: 'readonly',
        gameLoop: 'readonly',
        drawGameOverScreen: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
    },
  },
];
